using JonathonOH.RoadGeneration.Core;
using JonathonOH.Spatial;
using Other;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Serialization;

namespace JonathonOH.RoadGeneration
{
	/// <summary>
	/// Lifecycle
	/// 
	/// </summary>
	public class RoadSection : MonoBehaviour, IRoadSection
	{
		[SerializeField] public UnityEvent Created = new UnityEvent();
		[SerializeField] public UnityEvent Claimed = new UnityEvent();
		[SerializeField] public UnityEvent Removed = new UnityEvent();

		[SerializeField][ReadOnly] public int N;

		[FormerlySerializedAs("_startPoint")]
		[FormerlySerializedAs("startPoint")]
		[SerializeField] private Transform entry;
		[FormerlySerializedAs("_endPoint")]
		[FormerlySerializedAs("endPoint")]
		[SerializeField] private Transform exit;

		[SerializeField] protected internal MeshFilter _boundingMesh;
		[SerializeField] private bool _infiniteHeight = false;
		[SerializeField] public bool autoFlip = true;

		public TransformData Entry
		{
			get => TransformData.FromTransform(entry);
		}
		public TransformData Exit
		{
			get => TransformData.FromTransform(exit);
		}

		public bool IsFlipped
		{
			get
			{
				return transform.localScale.x < 0;
			}
			set
			{
				SetFlipped(value);
			}
		}

		[SerializeField][ReadOnly] public string autoGeneratedId;

		// private RoadSectionShape _shapeRelativeToStart
		// {
		// 	get
		// 	{
		// 		if (_localShapeReal == null) _SetShape();
		// 		return _localShapeReal;
		// 	}
		// 	set
		// 	{
		// 		_localShapeReal = value;
		// 	}
		// }
		// internal RoadSectionShape _localShapeReal;

		#region Pool callbacks
		internal void _OnCreated()
		{
			Created.Invoke();
			OnCreated();
		}
		internal void _OnClaimed()
		{
			Claimed.Invoke();
			OnClaimed();
		}
		internal void _OnRemoved()
		{
			Removed.Invoke();
			OnRemoved();
		}
		protected virtual void OnCreated() { }
		protected virtual void OnClaimed() { }
		protected virtual void OnRemoved() { }
		#endregion

		// private void _SetShape()
		// {
		// 	_localShapeReal = new RoadSectionShape();
		// 	_localShapeReal.Start = TransformData.FromTransform(startPoint);
		// 	_localShapeReal.End = TransformData.FromTransform(endPoint);
		// 	_localShapeReal.Start.Scale = Vector3.one;
		// 	_localShapeReal.End.Scale = Vector3.one;
		// 	_localShapeReal.SetBoundaryFromMesh(_boundingMesh.sharedMesh, TransformData.FromTransform(_boundingMesh.transform), _shapeRelativeToStart.Start, _infiniteHeight);
		// }

		public Mesh GetBoundaryInEntrySpace()
		{
			if (_boundingMesh == null || _boundingMesh.sharedMesh == null)
			{
				return null;
			}

			Mesh mesh = Instantiate(_boundingMesh.sharedMesh);
			TransformData entryTransform = Entry;
			Matrix4x4 entryWorldToLocal = Matrix4x4.TRS(entryTransform.Position, entryTransform.Rotation, Vector3.one).inverse;
			Matrix4x4 boundingMeshLocalToEntry = entryWorldToLocal * _boundingMesh.transform.localToWorldMatrix;
			Vector3[] vertices = mesh.vertices;

			for (int i = 0; i < vertices.Length; i++)
			{
				vertices[i] = boundingMeshLocalToEntry.MultiplyPoint3x4(vertices[i]);
			}

			mesh.vertices = vertices;
			mesh.RecalculateBounds();
			return mesh;
		}

		public void AlignStart(TransformData newStartPoint)
		{
			TransformData currentStart = TransformData.FromTransform(entry);
			Vector3 rotationChange = newStartPoint.Rotation.eulerAngles - currentStart.Rotation.eulerAngles;
			transform.RotateAround(currentStart.Position, Vector3.up, rotationChange.y);
			Vector3 positionChange = newStartPoint.Position - currentStart.Position;
			transform.position += positionChange;
			// ResetShape();
		}

		public void AlignEnd(TransformData newEndPoint)
		{
			TransformData currentEnd = TransformData.FromTransform(exit);
			Vector3 rotationChange = newEndPoint.Rotation.eulerAngles - currentEnd.Rotation.eulerAngles;
			transform.RotateAround(currentEnd.Position, Vector3.up, rotationChange.y);
			Vector3 positionChange = newEndPoint.Position - currentEnd.Position;
			transform.position += positionChange;
			// _SetShape();
		}

		// public RoadSectionShape GetShape()
		// {
		// 	return _shapeRelativeToStart;
		// }

		// public void ResetShape()
		// {
		// 	_shapeRelativeToStart = null;
		// }

		public void SetFlipped(bool flipped)
		{
			Vector3 localScale = transform.localScale;
			localScale.x = Mathf.Abs(localScale.x) * (flipped ? -1 : 1);
			transform.localScale = localScale;
		}

		public string GetFullId()
		{
			return autoGeneratedId + (IsFlipped ? "Flipped" : "");
		}

		// public RoadSectionShape GetRoadSectionShape()
		// {
		// 	return GetShape();
		// }

		public string GetShapeId()
		{
			return GetFullId();
		}
	}
}
