using System.Collections.Generic;
using JonathonOH.RoadGeneration.Core;
using JonathonOH.Spatial;
using Other;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Serialization;

namespace JonathonOH.RoadGeneration
{
	/// <summary>
	/// Lifecycle
	/// 
	/// </summary>
	public class RoadSection : MonoBehaviour, IRoadSection
	{
		[SerializeField] public UnityEvent Created = new UnityEvent();
		[SerializeField] public UnityEvent Claimed = new UnityEvent();
		[SerializeField] public UnityEvent Removed = new UnityEvent();

		[SerializeField][ReadOnly] public int N;

		[FormerlySerializedAs("_startPoint")]
		[FormerlySerializedAs("startPoint")]
		[SerializeField] private Transform entry;
		[FormerlySerializedAs("_endPoint")]
		[FormerlySerializedAs("endPoint")]
		[SerializeField] private Transform exit;

		[SerializeField] protected internal MeshFilter _boundingMesh;
		[SerializeField] private bool _infiniteHeight = false;
		[SerializeField] public bool autoFlip = true;

		public Pose Entry
		{
			get => PoseContructors.FromTransform(entry);
		}
		public Pose Exit
		{
			get => PoseContructors.FromTransform(exit);
		}

		public bool IsFlipped
		{
			get
			{
				return transform.localScale.x < 0;
			}
			set
			{
				SetFlipped(value);
			}
		}

		public bool IsBoundaryInfiniteHeight => _infiniteHeight;

		[SerializeField][ReadOnly] public string autoGeneratedId;

		#region Pool callbacks
		internal void _OnCreated()
		{
			Created.Invoke();
			OnCreated();
		}
		internal void _OnClaimed()
		{
			Claimed.Invoke();
			OnClaimed();
		}
		internal void _OnRemoved()
		{
			Removed.Invoke();
			OnRemoved();
		}
		protected virtual void OnCreated() { }
		protected virtual void OnClaimed() { }
		protected virtual void OnRemoved() { }
		#endregion

		public IEnumerable<Vector3> GetBoundaryPoints()
		{
			if (_boundingMesh != null && _boundingMesh.sharedMesh != null)
			{
				foreach (Vector3 meshVertex in _boundingMesh.sharedMesh.vertices)
				{
					yield return _boundingMesh.transform.TransformPoint(meshVertex);
				}
			}
		}

		public void AlignByEntry(Pose newEntry)
		{
			// Rotate
			Vector3 rotationChange = newEntry.rotation.eulerAngles - Entry.rotation.eulerAngles;
			transform.RotateAround(Entry.position, Vector3.up, rotationChange.y);

			// Translate
			Vector3 positionChange = newEntry.position - Entry.position;
			transform.position += positionChange;
		}

		public void AlignEnd(Pose newEnd)
		{
			// Rotate
			Vector3 rotationChange = newEnd.rotation.eulerAngles - Exit.rotation.eulerAngles;
			transform.RotateAround(Entry.position, Vector3.up, rotationChange.y);

			// Translate
			Vector3 positionChange = newEnd.position - Exit.position;
			transform.position += positionChange;
		}

		public void SetFlipped(bool flipped)
		{
			Vector3 localScale = transform.localScale;
			localScale.x = Mathf.Abs(localScale.x) * (flipped ? -1 : 1);
			transform.localScale = localScale;
		}

		public string GetFullId()
		{
			return autoGeneratedId + (IsFlipped ? "Flipped" : "");
		}

		public string GetShapeId()
		{
			return GetFullId();
		}
	}
}
